project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

files:
  - source: /translations/messages.pot
    translation: /translations/%locale%/LC_MESSAGES/messages.po
    update_option: update_as_unapproved
    languages_mapping:
      locale:
        pl-PL: pl
        de-DE: de
        es-ES: es
        fr-FR: fr
        it-IT: it
        ja-JP: ja
        pt-PT: pt
        pt-BR: pt_BR
        ru-RU: ru
        tr-TR: tr
        zh-CN: zh
