project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

files:
  - source: translations/messages.pot
    translation: translations/%locale_with_underscore%/LC_MESSAGES/messages.po
    update_option: update_as_unapproved
