project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

files:
  - source: translations/messages.pot
    translation: /%locale%/LC_MESSAGES/messages.po
    update_option: update_as_unapproved
    languages_mapping:
      locale:
        pl-PL: translations/pl
        de-DE: translations/de
        es-ES: translations/es
        fr-FR: translations/fr
        it-IT: translations/it
        ja-JP: translations/ja
        pt-PT: translations/pt
        pt-BR: translations/pt_BR
        ru-RU: translations/ru
        tr-TR: translations/tr
        zh-CN: translations/zh
