"""Add opensubtitles_api_key to User model

Revision ID: a64c82364d83
Revises: d0b36aa41da1
Create Date: 2025-05-21 12:40:31.950819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a64c82364d83'
down_revision = 'd0b36aa41da1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opensubtitles_api_key', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('opensubtitles_api_key')

    # ### end Alembic commands ###
